### ISSUE TITLE
coverage report only includes test files

### ISSUE THREAD

**Issue by tachtevrenidis** [Salakar/bridge#6]
I can run my detox tests and get a coverage report but it only includes coverage of the detox javascript files which are in the e2e/ folder. My app's js files are in the lib/ folder. How can I include those?

**Comment by Salakar** [comment]
We setup coverage include/exclude rules on RNFirebase tests in the following locations:

- https://github.com/invertase/react-native-firebase/blob/master/bridge/.babelrc#L25
- https://github.com/invertase/react-native-firebase/blob/master/bridge/package.json#L54

Additionally we add the lib (up one directory) as a project root to the metro bundler config so we don't have to copy it into the test project directory (`/bridge` in our case) - this is how the coverage is picked up;

- https://github.com/invertase/react-native-firebase/blob/master/bridge/rn-cli.config.js
- https://github.com/invertase/react-native-firebase/blob/master/bridge/.babelrc#L12

For the alias to work you need to include your lib's dependencies in your test projects dependencies and make sure they're listed here: https://github.com/invertase/react-native-firebase/blob/master/bridge/rn-cli.config.js#L17

(`dist` in both cases above is from the root of the lib - the lib's build output - in your case if you have no build step then this would just be `lib`)

Apologies for lack of docs - it's still very early on 🙈

**Comment by tachtevrenidis** [comment]
will give that a shot. No worries on docs, this is a great project. Good job!

**Comment by tachtevrenidis** [comment]
FWIW I am using Haul not Metro :-)

**Comment by Salakar** [comment]
Not used Haul myself, but hopefully it has the same potential as above, you should definitely be able to get coverage going at least in metro as we do (in the slow process of migrating our old tests into it); hopefully the same can work in Haul - let me know your findings and we can add it to the never ending list of docs todo 🙈 

![image](https://user-images.githubusercontent.com/5347038/39439650-3a899886-4ca0-11e8-9af9-eb51574f09d2.png)

**Comment by tachtevrenidis** [comment]
still not quite there yet. Am I to understand that when my detox tests are running, my whole app in the lib dir (index.ios.js) needs to be loaded (so for example a require("MyApp") would succeed?)

**Comment by Salakar** [comment]
Files you want to test won't get bundled unless you require them e.g. we require the RNFirebase lib in the root view to include it in the bundler: https://github.com/invertase/react-native-firebase/blob/master/bridge/app.js

Are you trying to test a RN module or an app?

**Comment by tachtevrenidis** [comment]
RN module (part of a larger, native app). TSX files are in src/, generated JS files in lib/, detox js files in e2e/. I wrote a test that launches the app, navigates to the RN module, assets etc, this all works.

**Comment by Salakar** [comment]
Yep, so you'll need to require everything that you need to use inside your app code and not the tests, you can then use bridge.require in your tests if you then need access to those files/modules there otherwise they'll never get bundled.

e.g.: https://github.com/invertase/react-native-firebase/blob/master/bridge/e2e/firestore/path.e2e.js#L5

**Comment by Salakar** [comment]
Just a note that the paths are full paths from project root when using bridge.require as it internally just looks at the bundles webpack modules map, the fn source code is here: https://github.com/invertase/bridge/blob/master/lib/node/index.js#L22 looks like it doesn't auto add .tsx file extensions when checking there so you may need to give the full name including extension or add support to the require util there 😋

**Comment by tachtevrenidis** [comment]
when i add the require to my test: `const MyModule = bridge.require('lib/MyModule');`
I get:

`Error: Context not available - bridge.require must be used inside your individual tests, not in the global or module scope`

**Comment by tachtevrenidis** [comment]
by perusing your tests, I think maybe I misunderstood the purpose of this. My goal was to be able to 'run' our app in the simulator, use the tests to assert and interact with the UI, and finally get a coverage report on the RN code that was executed. Is this possible? From what I see your tests are just using certain pieces of your app, execute methods and assert on data returned.

**Comment by Salakar** [comment]
Whilst your use case isn't exactly the primary one for bridge there's shouldn't be anything stopping you from using it to augment coverage - you just need to do it the same way as you would on detox but with bridge imported + coverage stuff setup as above. Or; you can also individually import specific views and mount them by manipulating state of your root view if you wanted to go that approach, I toyed with this idea when making bridge:

Add a line in your root view constructor, just like [this one](https://github.com/invertase/react-native-firebase/blob/master/bridge/app.js#L19) with the below:

```js
bridge.setBridgeProperty('root', this);
```

`bridge.root` inside your tests is now your root component which you can manipulate, e.g. this test doing a setState test on the root view of the app when I first toyed with the idea: [bridge.spec.js#L40](https://github.com/invertase/react-native-firebase/blob/master/bridge/e2e/bridge.spec.js#L40)

Re the `const MyModule = bridge.require('lib/MyModule');` - the error basically means that you're trying to require outside of a test runner function - you should do your requires inside each test function as the bridge isn't available immediately i.e. outside in the module scope, but it is guaranteed to be there in each test. The same goes for most bridge.X / anything set via `bridge.setBridgeProperty()`.

**Comment by Salakar** [comment]
On that, `bridge.setBridgeProperty('someName', someThing);` allows you to expose anything to your tests - you set it in app code and it becomes available in your test code via `bridge.someName` - again though access the properties you set inside each individual test runner/function - as it's only available inside each test but not outside the test runner/function as there can be reloads, app launches etc between tests.

**Comment by tachtevrenidis** [comment]
thanks for all the info. I will give it a shot. For the record, I put the `bridge.require` right under the 'it' line (as your example showed) not in some global scope.

**Comment by Salakar** [comment]
That's weird, that error only throws if RN context doesn't exist: [lib/node/index.js#L25](https://github.com/invertase/bridge/blob/master/lib/node/index.js#L25), the only time it doesn't exist is between first app load, app reloads and app launches, but I've added hooks to all those events to then attach bridge on, do you have a global `before` tests hook setup with detox.init(), e.g. : [e2e/init.js#L5](https://github.com/invertase/react-native-firebase/blob/master/bridge/e2e/init.js#L5)

Or, unless you're calling a method on detox that I've missed out on patching, here's where I patch them: https://github.com/invertase/bridge/blob/master/lib/node/patch/detox.js

 - init
 - cleanup
 - reloadReactNative
 - launchApp

Am I missing one that you're using?

**Comment by tachtevrenidis** [comment]
our init files looks identical (except for the firebase stuff). My test file 'beforeEach' looks like:
```
beforeEach(async () => {
    await device.launchApp({ delete: true });
    await waitFor(element(by.id('MyView'))).toBeVisible().withTimeout(1000);
  });
```

**Comment by Salakar** [comment]
Hmm might be a bit of a race condition then potentially, weird one though as I do [defer the event here](https://github.com/invertase/bridge/blob/master/lib/node/context.js#L62) on node to at least the next event loop, you could try up the `1` to something like `250` - and if that solves it then it's deffo a race condition that I can look into it solving.

Thanks for trying out these things btw 👍

**Comment by tachtevrenidis** [comment]
sure (no prob). Also keep in mind that "MyView" from the test above is a NATIVE view (not react native). Tapping on that loads the RN bridge and eventually the component.

**Comment by tachtevrenidis** [comment]
maybe over the weekend I will try to create a small sample of what I am trying to do and make it public so you can take a look. (I still don't have it working but have not tried your latest advice)

**Comment by Salakar** [comment]
> **Bridge has moved to [invertase/jet](https://github.com/invertase/jet) and is in the process of being reworked. This repo will remain here as a reference for anyone currently using Bridge/Jet as is.**
